#!/bin/bash 

fn=$(echo "$(openssl rand -hex 10).tmp")

qalc | tee $fn

res=$(ansifilter -p $fn | sed -n 's/^.*[=≈]//p; s/[[:blank:]]//g' | tail -n1)

res=$(echo $res | sed "s/−/-/g")

echo -n $res | nohup xclip -selection clipboard > /dev/null 2>&1
rm $fn

#sleep 5
